### ISSUE TITLE
Getting addcollaborators to work

### ISSUE THREAD

**Issue by brianamarie** [brianamarie/practice-sinatra#1]
Alrighty - I have everything with this [basics.rb](https://github.com/brianamarie/practice-sinatra/blob/master/basics.rb) script running as expected, **except** for the call of the [addcollaborators](https://github.com/brianamarie/practice-sinatra/blob/master/addcollaborators) script. 

I have this running locally by 
- ensuring the webhook link in settings matches the output of `./ngrok http 4567`
- running `ruby basics.rb` from the correct directory

Does anyone have any ideas/thoughts on how to make this work? @stoe @hectorsector @brntbeer @crichID @hollenberry @beardofedu

**Comment by stoe** [comment]
@brianamarie, you need to make the addcollaborators script executable.

chmod +x addcollaborators

## 

_Stefan Stölzle https://de.linkedin.com/in/stefanstoelzle_
Services Engineer
Github, Inc.
https://github.com | https://services.github.com

**Comment by brianamarie** [comment]
> @brianamarie, you need to make the addcollaborators script executable.
> 
> chmod +x addcollaborators

@stoe 😍 Awesome, thank you! I did this and also added 'system', so that block looks like this: 

```
post '/payload' do
  system '/addcollaborators -r brianamarie/travel-log -i 8'
  push = JSON.parse(request.body.read)
  puts "I got some JSON: #{push.inspect}"
end
```

Still isn't working, but I think that's the right direction to be going....

**Comment by stoe** [comment]
@brianamarie, is the path to addcollaborators correct?
Looks like with the / in front it would look in the root folder of the
system it's running on.
I think it should be ./addcollaborators

## 

_Stefan Stölzle https://de.linkedin.com/in/stefanstoelzle_
Services Engineer
Github, Inc.
https://github.com | https://services.github.com

**Comment by brianamarie** [comment]
> I think it should be ./addcollaborators

@stoe Great point, thank you! I made that change, but still same results:

```
post '/payload' do
  system './addcollaborators -r brianamarie/travel-log -i 8'
  push = JSON.parse(request.body.read)
  puts "I got some JSON: #{push.inspect}"
end
```

The script should still be able to access my token for GitHubTeacher, right?

**Comment by brianamarie** [comment]
Closing this out, because it works now! 👍 🎉 🙇 ✨ 🌈 🐴
